[build]
  publish = "."
  command = ""

[[redirects]]
  from = "http://enzest.com/*"
  to = "https://www.enzest.com/:splat"
  status = 301
  force = true

[[headers]]
  for = "/*"
    [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Cache-Control = "public, max-age=31536000"
